### ISSUE TITLE
[Compose Web]: TypeError: content is not a function

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#5045]
Having issue on web after upgrading compose version from 1.7.0-dev1686 to new versions > 1.7.0-dev1698

<img width="705" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/36570577/9a7bb35d-2f1f-4e2e-a9d1-c368b2f0ab6b">

**Comment by arkivanov** [comment]
Also bumped into this crash.

**Comment by rustamsmax** [comment]
@terrakok even after upgrading to the latest version 1.7.0-alpha01 the issue still exists

**Comment by CanizaresSoftwares** [comment]
Using kotlin version 2.1.0-dev-875 from maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev") issue is not present.

**Comment by PMARZV** [comment]
Workaround to this issue is to use Kotlin 1.9.22 or 2.0.10-RC-510 (available with maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/")).
This is the associated Slack conversation : https://kotlinlang.slack.com/archives/C01F2HV7868/p1720105526946439?thread_ts=1720098055.793059&cid=C01F2HV7868

**Comment by eymar** [comment]
I can confirm, that CfW 1.7.0-xyz and newer builds will work only with kotlin 2.0.10 or 1.9.24 (using compose compiler 1.5.14.1-beta02 or newer versions when they appear).

Kotlin 2.0.10 contains a necessary fix, which is present in kotlin 2.0.0. 
For convenience, the fix is backported to the compose compiler for 1.9.24.

**Comment by eymar** [comment]
I'm closing this one as I see no particular actions on our side, except suggesting to use a correct Kotlin version (Please see the comment above). 
Feel free to add more questions or reopen if needed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5045">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
