### ISSUE TITLE
Compile error in kmp Android target after upgrading to 1.5.0-rc01

### ISSUE THREAD

**Issue by pablichjenkov** [JetBrains/compose-multiplatform#3531]
When adding below line of code used for Composable Preview in Android sourceset, the build fails.

```
buildFeatures {   
    compose = true    
}
```

Compilation fails with bellow message:
```
> Task :shared:compileDebugKotlinAndroid FAILED
e: java.lang.ClassCastException: Cannot cast androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar to org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar
```

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add bellow line in gradle android dsl
```
buildFeatures {   
    compose = true    
}
```
2. Try to build the Android App.

**Expected behavior**
App should build ok

**Comment by pablichjenkov** [comment]
Forgot to mention the offending lines are needed for preview in Android Studio. So basically this issue prevents Preview in Android Studio.

**Comment by dima-avdeev-jb** [comment]
Can you please create a minimal reproducer project what will works with 1.4.3 and build with this error on 1.5.0-rc01 ?

**Comment by gastsail** [comment]
hey @pablichjenkov please check this last answer on my question 

https://github.com/JetBrains/compose-multiplatform/issues/3499

**Comment by fernandozanutto** [comment]
I tried to update to 1.5.0-rc01 and it also fails for me. 

Until beta02 everything seems to work fine (even though beta02 has a dependency that makes me use Android API 34, but build result in success after changing android api)

Build fails in rc01: https://github.com/fernandozanutto/water-reminder/tree/build-fails-compose-1.5.0-rc01

Build success in beta01: https://github.com/fernandozanutto/water-reminder/tree/build-success-compose-1.5.0-beta01

**Comment by pablichjenkov** [comment]
Hi @dima-avdeev-jb 
Here is a reproducible using JB template: https://github.com/pablichjenkov/cmp_issue_3531_repro
1.4.3 works fine, the last commit message list the steps of things that upgrade. Basically Android targetSDK to 34.

**Comment by pablichjenkov** [comment]
With **1.5.0-rc01**, `@Preview` on Desktop seems to be broken too.

**Comment by mazunin-v-jb** [comment]
@pablichjenkov, does enabling `@Preview` on desktop cause compilation error too? Or just not working?
Android issue has been reproduced, thanks.

**Comment by pablichjenkov** [comment]
@mazunin-v-jb 
Compiles and runs is good. The Preview is the one not working. It shows an error, not sure if is better to open another issue for that.

**Comment by mazunin-v-jb** [comment]
@pablichjenkov If it works on 1.4.3 on desktop and doesn't work on 1.5.0-rc01, you may describe the error here: attach the screenshot and small reproducer, please. I guess, no need to create a new one, you may [update your existing one](https://github.com/pablichjenkov/cmp_issue_3531_repro) by new commits for desktop.

If it doesn't work on 1.4.3, it would be better to submit another issue. And another reproducer :)

**Comment by pablichjenkov** [comment]
Hi @mazunin-v-jb 
Sorry for misleading on the desktop target comment, it seems to be a different thing. The error seems to be associated with using in the Composable code.

```kotlin
Window(
      state = windowState,
      onCloseRequest = { onExitClick() }
  ) {
      MenuBar {
           ...
     }
}
```
Once I removed that part from the Composable the Preview works ok.
I will ask in kotlinlang slack and if I don't find an answer I open a new issue. But I don't think rendering desktop window menus is supported by the desktop previewer.

**Comment by gastsail** [comment]
I updated to 1.5.0-rc01 and it also fails with 

`java.lang.ClassCastException: Cannot cast androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar to org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar`

**Comment by Aidanvii7** [comment]
Seeing the same. This breaks android previews for me (using them as desktop previews are too limited).

**Comment by Nailik** [comment]
Same issue here, i need android compose for Glance Widget as it is not supported by compose-multiplatfom.

**Comment by kaszabimre** [comment]
I've updated to `1.5.0-rc04` and it also fails with the same error:

```
java.lang.ClassCastException: Cannot cast androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar to org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar
```

`beta02` the latest working version for me

**Comment by Nailik** [comment]
This issue is solved by upgrading to androidx.compose.compiler 1.5.2

**Comment by gastsail** [comment]
I think we should have a compatibility table on the repo readme in the future, so we can follow along when updating.

**Comment by pablichjenkov** [comment]
I just confirmed is working like a charm now! 
Closing it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3531">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
