### ISSUE TITLE
`IllegalStateException: IrPropertyPublicSymbolImpl` error in latest release - 1.6.0-beta01

### ISSUE THREAD

**Issue by rdsarna** [JetBrains/compose-multiplatform#4174]
**Describe the bug**
Building the iOS app via a Release build configuration fails after updating to the latest `1.6.0-beta01` version.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): iOS 16
- OS architecture (x86 or arm64): arm64

**To Reproduce**
A KMM project with the latest compose beta - `1.6.0-beta01`. (I tried with a project built with [Compose Multiplatform Wizard](https://terrakok.github.io/Compose-Multiplatform-Wizard/))
Build iOS project via the Release Configuration (not debug)

The following error is seen during build -
```
java.lang.IllegalStateException: IrPropertyPublicSymbolImpl for androidx.collection.internal/EMPTY_INTS|6945326639149902205[0] is already bound: PROPERTY name:EMPTY_INTS visibility:internal modality:FINAL [val]
```

~~It seems like the following has been introduced in the latest release that is conflicting with a property of same name in `androidx.collection`. (might be wrong about the exact cause)~~
```
package androidx.compose.ui.text.caches

/**
 * Copied from ContainerHelpers.binarySearch until collection2 can be linked
 */
@kotlin.jvm.JvmField
internal val EMPTY_INTS = IntArray(0)
```

**Comment by rdsarna** [comment]
Looking into it a little bit more and comparing `1.5.11` to `1.6.0-beta01`, the above mentioned code from the `androidx.compose.ui.text.caches` package doesn't seem to be new. It does exist in 1.5.11.

Instead, it looks like `androidx.collection` was added as a dependency in `1.6.0-beta01`. 

Here are references to `EMPTY_INTS` in version `1.5.11` -
<img width="669" alt="Screenshot 2024-01-26 at 2 47 52 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/7789307/b748c28c-f77b-4db4-af2e-2d0a9e871aae">

And here are references to `EMPTY_INTS` in version `1.6.0-beta01` -
<img width="1054" alt="Screenshot 2024-01-26 at 2 46 57 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/7789307/54e99aae-9a70-46e5-8a26-14dccc36416b">

Sorry for the limited info, I haven't been able to dig too deep into this.

**Comment by eymar** [comment]
What libraries did you choose when configuring the porject in the wizard (here https://terrakok.github.io/Compose-Multiplatform-Wizard/)?
Could you please share the project you generated where the issue can be reproduced?

**Comment by rdsarna** [comment]
> What libraries did you choose when configuring the porject in the wizard (here https://terrakok.github.io/Compose-Multiplatform-Wizard/)? Could you please share the project you generated where the issue can be reproduced?

I've pushed the sample project that was exhibiting the issue to Github - https://github.com/rdsarna/Multiplatform-App-Issue-Example

**Comment by chrislacy** [comment]
My project is experiencing this in [v1.6.0-beta02](https://github.com/JetBrains/compose-multiplatform/tree/v1.6.0-beta02) also.

**Comment by eymar** [comment]
right, the proper fix didn't make to 1.6.0-beta2.

The possible temporary workaround could be to not use androidx.annotation:annotation and androidx.collection, but use 
org.jetbrains.compose.annotation-internal:annotation and org.jetbrains.compose.collection-internal:collection instead.
It could be that you don't use it directly, but it's a transitive dependency. Then gradle dependencies substitution should help.

The proper fix is in progress.

**Comment by sureshmaidaragi1919** [comment]
@eymar any fixes done latest release 1.6.2?

**Comment by eymar** [comment]
> @eymar any fixes done latest release 1.6.2?

Should work in 1.6.0

**Comment by sureshmaidaragi1919** [comment]
@eymar  it showing  even updating to v1.6.2

```
Compilation failed: IrPropertyPublicSymbolImpl for androidx.collection.internal/EMPTY_INTS|{}EMPTY_INTS[0] is already bound: PROPERTY name:EMPTY_INTS visibility:internal modality:FINAL [val]

 * Source files: 
 * Compiler version: 1.9.22
 * Output kind: FRAMEWORK
```

**Comment by eymar** [comment]
@sureshmaidaragi1919 There's no Compose Multiplatform 1.6.2, there is only 1.6.0

**Comment by sureshmaidaragi1919** [comment]
Sorry my bad, I used 1.6.0 for KMM.
Btw thank you, I found the root cause is because of another dependency `Koin` using older version of compose, So I need to either downgrade or should wait for koin to update, [here is the full discussion](https://github.com/Tlaster/PreCompose/issues/272#issuecomment-1970619782)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4174">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
