### ISSUE TITLE
java.lang.NoSuchMethodError when updated to 0.1.0-dev87

### ISSUE THREAD

**Issue by CommanderTvis** [JetBrains/compose-multiplatform#16]
```kotlin
Exception in thread "main" java.lang.NoSuchMethodError: 'void androidx.compose.desktop.AppWindowKt.Window-RCQARxQ$default(java.lang.String, long, long, boolean, java.awt.image.BufferedImage, boolean, androidx.compose.desktop.WindowEvents, kotlin.jvm.functions.Function0, kotlin.jvm.functions.Function2, int, java.lang.Object)'
	at io.github.commandertvis.calc.AppKt.main(App.kt:20)
	at io.github.commandertvis.calc.AppKt.main(App.kt)

Process finished with exit code 1

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5629">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
