### ISSUE TITLE
iOS build fails with Duplicate Symbols Error when upgraded to 1.6.2

### ISSUE THREAD

**Issue by Vaibhav2002** [JetBrains/compose-multiplatform#4723]
**Describe the bug**
iOS build fails with `Duplicate Symbols` error when upgraded from 1.5.11 to 1.6.2

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): MacOS Sonoma 14.4.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iOS SImulator 17.4

**Additional context**
When I upgraded my project from Compose Multiplatform 1.5.11 to 1.6.2, iOS builds start failing with Duplicate Symbols issue,
it shows duplicate symbols in 2 of my modules, 2nd module being a grand child module of the first

#### This is the error
```
duplicate symbol '_OBJC_METACLASS_$_CMPViewController' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2665](CMPViewController.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2665](CMPViewController.o)
duplicate symbol '_OBJC_CLASS_$_CMPViewController' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2665](CMPViewController.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2665](CMPViewController.o)
duplicate symbol '_OBJC_IVAR_$_CMPViewController._lifecycleState' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2665](CMPViewController.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2665](CMPViewController.o)
duplicate symbol '_OBJC_METACLASS_$_CMPAccessibilityElement' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2667](CMPAccessibilityElement.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2667](CMPAccessibilityElement.o)
duplicate symbol '_OBJC_CLASS_$_CMPAccessibilityContainer' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2666](CMPAccessibilityContainer.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2666](CMPAccessibilityContainer.o)
duplicate symbol '_OBJC_CLASS_$_CMPAccessibilityElement' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2667](CMPAccessibilityElement.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2667](CMPAccessibilityElement.o)
duplicate symbol '_OBJC_METACLASS_$_CMPAccessibilityContainer' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2666](CMPAccessibilityContainer.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2666](CMPAccessibilityContainer.o)
duplicate symbol '_OBJC_IVAR_$_CMPAccessibilityElement._inDealloc' in:
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/build/cocoapods/framework/shared.framework/shared[arm64][2667](CMPAccessibilityElement.o)
    /Users/vaibhav/Projects/Medial/MedialMultiplatform/shared/ui/screens/build/cocoapods/framework/shared_ui_screens.framework/shared_ui_screens[arm64][2667](CMPAccessibilityElement.o)
ld: 8 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### This is my module structure 
<img width="283" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/64367926/4dcae5ae-0c57-4434-863f-64bb7f5bfce2">

**Comment by ASalavei** [comment]
Hi!
We're using CMPUIKit static library in compose framework. I would recommend to use only one top-level dependency of Multiplatform framework. In your case if `shared-ui-screens` uses `shared-ui` as dependency, I would include only the first one into iOS App, and [propagate](https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries) symbols from dependent `shared-ui`.

Also, you can provide minimum viable repro application to let us make close look into it.

**Comment by Vaibhav2002** [comment]
Hi,
`shared-ui` module uses `shared-ui-screens` as an `implementation` dependency
Same, `shared` uses `shared-ui` as an `implementation` dependency

**Comment by ASalavei** [comment]
Could you please remove everything valuable from your project and upload minimal sources set on GitHub to do proper investigation?

**Comment by ASalavei** [comment]
Thank you for the reproducer. I can see you're using 4 frameworks added via CocoaPods to you iOS app.
It's recommended to create [umbrella](https://kotlinlang.org/docs/native-spm.html#exporting-multiple-modules-as-an-xcframework) framework to solve this issue. Also you can use [export](https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries) dependencies to propagate symbols to your umbrella framework.
As a bonus, you will get reduced application size and launch time.

**Comment by Vaibhav2002** [comment]
> Thank you for the reproducer. I can see you're using 4 multiplatform frameworks added via CocoaPods to you iOS app.
> It's recommended to create [umbrella](https://kotlinlang.org/docs/native-spm.html#exporting-multiple-modules-as-an-xcframework) framework to solve this issue. Also you can use [export](https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries) dependencies to propagate symbols to your umbrella framework.
> As a bonus, you will get reduced application size and faster launch time.
> 
> 

The pod dependencies in all those child modules which are exported as a separate framework is not actually used in the iOS native side, but only within the shared module.

Do i still need to include those in the umbrella framework?
Do i also need to include all other child modules, even those which dont have any pod dependencies?

I only need the files from the parent "shared" module in iOSApp, none from the child modules.

**Comment by ASalavei** [comment]
> I only need the files from the parent "shared" module in iOSApp, none from the child modules. Thats why I have used implementation() everywhere instead of api()

Hmm.. your iOS app currently depends on 4 frameworks that was build from different modules. Do you really need these dependencies? If you can remove safely all except one, then the issue will be solved.

**Comment by Vaibhav2002** [comment]
> > I only need the files from the parent "shared" module in iOSApp, none from the child modules. Thats why I have used implementation() everywhere instead of api()
> 
> Hmm.. your iOS app currently depends on 4 frameworks that was build from different modules. Do you really need these dependencies? If you can remove safely all except one, then the issue will be solved.

I tried, but then I get Undefined Symbols issue 
Mentioning some files of Ably, Reachability, Amplitude and other pods

**Comment by ASalavei** [comment]
It means your iOS app does not know where to find these frameworks. Something (Someone) should tell this info to iOS app via `Build Settings > Framework Search Paths`. Maybe it can be done using `podespec` of the `shared` framework - see script inside each file. Unfortunately I don't know how to do it exactly, but it definitely the way to go. Try to ask in our Slack channels: https://kotlinlang.slack.com/archives/C3PQML5NU  https://kotlinlang.slack.com/archives/C0346LWVBJ4

Btw, the `Podfile` you shared looks OK until you are using dynamic frameworks (`use_frameworks!` option).

**Comment by Vaibhav2002** [comment]
Thanks for the help @ASalavei 
I will check this out

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4723">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
