### ISSUE TITLE
Compose-desktop @Preview fails to show preview which uses kotlin.time.Duration

### ISSUE THREAD

**Issue by vdshb** [JetBrains/compose-multiplatform#2473]
Desktop previewer fails to show a preview for this snippet:

```kotlin
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.runtime.Composable
import kotlin.time.Duration.Companion.minutes

@Preview
@Composable
fun Reproducer(
) {
    1.minutes
}
```
An exception occurs:

```
   ...
Caused by: java.lang.NoSuchMethodError: 'long kotlin.time.DurationKt.toDuration(int, kotlin.time.DurationUnit)'
	at duration.ReproduceKt.Reproducer(Reproduce.kt:17)
   ...
```

kotlin version: 1.7.20
compose version: 1.3.0-alpha01-dev853

**Comment by vdshb** [comment]
Not an expert, but for me it looks like previewer is build on some old kotlin version like 1.5.0 or something.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2473">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
